app/components/search/DatePickerSelector.jsx
app/components/search/DateRangeSelector.jsx

DatePicker working branch

---

app/components/collection/CollectionAnalyser.jsx
app/components/collection/CollectionStats.jsx
app/components/search/AggregationCreator.jsx

This ticket, divided into 3 separated tasks has been done for parts 1 and 2. Part 3 is block because of dependencies that need to be addressed before development can proceed to it.
A more detailed explanation can be found at:
[https://github.com/CLARIAH/wp5_mediasuite/issues/68](url)

Issue 68. Change automatic metadata labels

---

app/components/collection/CollectionAnalyser.jsx
app/components/search/QueryBuilder.jsx
sass/_components.scss

make search icon in search field trigger a search request.

#129 Search button in query box does not work

---

app/ComparativeSearchRecipe.jsx
app/components/collection/CollectionAnalyser.jsx
app/components/search/QueryFactory.jsx
app/components/stats/QueryComparisonLineChart.jsx
app/util/ElasticsearchDataUtil.js
package.json

Replace current line chart graph by Recharts component.

Replace current Line chart graph by Recharts component

---

app/components/stats/Histogram.jsx
package.json

Replace current D3-react Histogram implementation by using open source react-D3 component called Recharts
[ReCharts](http://recharts.org/#/en-US)

Replace Histogram by an open source component. ReCharts

---

app/components/search/DateRangeSelector.jsx

Now the selection list sorts alphabetically the fields selection

#170 Sort alphabetically the list of metadata fields

---

app/components/collection/CollectionSelector.jsx
sass/_powerSelect.scss
sass/labo-components.scss

Enable search in collection selector

Enable search in collection selector

---

app/components/search/ItemDetails.jsx
app/components/search/MetadataTablePreview.jsx
app/components/search/SearchHit.jsx
app/components/search/SearchSnippet.jsx
sass/_bootstrap-overrides.scss

Improve detailed viewer and the result list and add pointer cursor for heading on searchHit

#49 Improve detailed viewer and the result list

---

sass/_components.scss

minor update to fix labels colors based on bootstrap class label-*

update viewer component autosuggest dropdown

---

app/components/helpers/BreadCrumbs.jsx
app/components/helpers/BulkActions.jsx
app/components/helpers/Export.jsx
app/components/helpers/Pagination.jsx
app/components/projects/AnnotationRow.jsx
app/components/projects/AnnotationView.jsx
app/components/projects/BookmarkRow.jsx
app/components/projects/BookmarkTable.jsx
app/components/projects/BookmarkView.jsx
app/components/projects/ItemDetailsModal.jsx
app/components/projects/ProjectBookmarks.jsx
app/components/projects/ProjectCreate.jsx
app/components/projects/ProjectDetails.jsx
app/components/projects/ProjectEdit.jsx
app/components/projects/ProjectForm.jsx
app/components/projects/ProjectSelector.jsx
app/components/projects/ProjectSessions.jsx
app/components/projects/ProjectTable.jsx
app/components/projects/ProjectWrapper.jsx
app/components/projects/ProjectsOverview.jsx
app/components/projects/SortTable.jsx
app/util/AnnotationUtil.js
package.json

Feel free to add it in 2018, as it doesn't contain important bug fixes of major improvement. It mainly improves the code quality of our contributions.

Code quality and some minor improvements

---

app/components/search/MetadataTable.jsx

Add name/label of date field in the resource viewer

Add name/label of date field in the resource viewer

---

app/components/search/AggregationBox.jsx

Add tooltip to identify facets fields

#282 Add tooltip to identify facets fields

---

app/SingleSearchRecipe.jsx
app/components/search/AggregationList.jsx
app/components/search/DatePickerSelector.jsx
app/components/search/QueryBuilder.jsx
sass/_components.scss
sass/_react-datepicker.scss

Implement list view for facets display (issue #107)
Since the selection between tabs and list is driven by the this.props.recipe.ingredients.aggregationView to test you can modify those values in SingleSearchRecipe.jsx 
for: this.props.recipe.ingredients.aggregationView (L:504)
and where this.props.aggregationView === 'box' in QueryBuilder.jsx
(2 places)

Implement list view for facets display

---

app/components/search/AggregationList.jsx
sass/_components.scss

#361 Add Empty aggregation to the list with message
https://app.zenhub.com/workspace/o/clariah/wp5_mediasuite/issues/361

#361 Add Empty aggregation to the list with message

---

sass/_components.scss

Updated media queries to account for big numbers in paging while resizing.

Update media queries to count big numbers in paging

---

app/ItemDetailsRecipe.jsx
app/api/SearchAPI.js
app/collection/mappings/CollectionConfig.js
app/components/collection/CollectionSelector.jsx
app/components/player/annotation/AnnotationTimeline.jsx
app/components/player/audio/HTML5AudioPlayer.jsx
app/components/player/segmentation/SegmentationTimeline.jsx
app/components/player/transcription/Transcriber.jsx
app/components/player/video/FlexPlayer.jsx
app/components/player/video/HTML5VideoPlayer.jsx
app/components/player/video/JWPlayer.jsx
app/components/player/video/VimeoPlayer.jsx
app/components/player/video/YouTubePlayer.jsx
app/components/search/QueryBuilder.jsx
app/model/QueryModel.js
app/util/AnnotationUtil.js
sass/_components.scss

mostly was updated to support:
- searching through speech transcripts within the same index
- showing all carriers as a playlist on the resource viewer
- annotation of these different carriers

Multi search overhaul

---

app/CollectionRecipe.jsx
app/ComparativeSearchRecipe.jsx
app/QueryComparisonRecipe.jsx
app/SingleSearchRecipe.jsx
app/collection/mappings/CollectionConfig.js
app/components/collection/CollectionAnalyser.jsx
app/components/collection/FieldSelector.jsx
app/components/search/DateRangeSelector.jsx
app/components/search/QueryBuilder.jsx
app/components/workspace/personalcollections/CollectionCreateView.jsx
app/components/workspace/personalcollections/CollectionEditView.jsx
app/components/workspace/personalcollections/CollectionListView.jsx
app/components/workspace/projects/annotation/ProjectAnnotationView.js
app/components/workspace/projects/bookmark/ProjectBookmarkView.jsx
app/components/workspace/projects/crud/ProjectCreateView.jsx
app/components/workspace/projects/crud/ProjectDetailsView.jsx
app/components/workspace/projects/crud/ProjectEditView.jsx
app/components/workspace/projects/crud/ProjectListView.jsx
app/components/workspace/projects/query/ProjectQueriesTable.jsx
app/components/workspace/projects/query/ProjectQueriesView.jsx
app/components/workspace/projects/session/ProjectSessionCreateView.jsx
app/components/workspace/projects/session/ProjectSessionView.jsx
package.json
sass/_components.scss

- The feature specific documentation (opened using the blue ?-button on the top right) is now retrieved via the media suite. It reuses parts of the main documentation.
- Also some other minor fixes.

Feature specific documentation for all recipes

---

app/components/search/AggregationList.jsx

Fix issue with facets not being added to the list

Fix issue with new facets not being added to aggregation list

---

app/QueryComparisonRecipe.jsx
app/components/search/QueryBuilder.jsx
app/components/stats/Histogram.jsx

Enable relative values for barcharts in Histogram.
Issue: https://app.zenhub.com/workspace/o/clariah/wp5_mediasuite/issues/475

Enable relative values for barcharts in Histogram

---

sass/search/AggregationList.scss

Re-style facet headers for long titles. 
The implemented solution is basically truncate string with ellipsis (...)

Re-style facet headers for long titles

---

app/QueryComparisonRecipe.jsx
app/components/workspace/projects/query/ProjectQueriesTable.jsx

github issue:
https://app.zenhub.com/workspace/o/clariah/wp5_mediasuite/issues/498

move compare queries btn to bulkActions bar in query comparison tool

---

app/components/workspace/projects/query/ProjectQueriesTable.jsx
app/model/QueryModel.js
sass/workspace/components/_queryInfoTooltip.scss
sass/workspace/index.scss

Add tooltip to saved queries in workspace project table:

#440 Expose saved queries in project table in the workspace

---

app/ItemDetailsRecipe.jsx
app/SingleSearchRecipe.jsx
app/api/LinkedDataAPI.js
app/collection/mappings/CollectionConfig.js
app/components/linkeddata/LDResourceViewer.jsx
sass/linkeddata/LDResourceViewer.scss
sass/recipes/ItemDetailsRecipe.scss

after merging, deactivate in master

Lod rekindle

---

app/components/search/Paging.jsx

@jblom : This pull request refers to the issue on the paging component when clicking the next button.

fix issue in paging with btn next

---

app/SingleSearchRecipe.jsx
app/components/search/SearchHit.jsx
sass/search/SearchHit.scss

Flag already bookmarked elements in SearchHits list.

Flag already bookmarked elements in SearchHits list

---

app/SingleSearchRecipe.jsx
app/components/search/SearchHit.jsx
app/util/ComponentUtil.js
sass/search/SearchHit.scss
webpack_envs/webpack.development.js

@jblom : Visited links have a color to show the user that they have already been visited

PR: change color of visited links

---

app/components/search/SearchHit.jsx

Issue: https://app.zenhub.com/workspaces/main-board-5bd99e4e4b5806bc2befbe27/issues/beeldengeluid/labo-components/199

#199 Fix issue when clicking Quick view btn in SearchHits list

---

sass/_mixins.scss
sass/search/AggregationList.scss

@lilimelgar @jblom : Update to issue https://app.zenhub.com/workspaces/main-board-5bd99e4e4b5806bc2befbe27/issues/beeldengeluid/labo-components/175 
switch btn styling adjustements.

update switch btn stylings

---

app/components/stats/CollectionInspectorLineChart.jsx

issue:
https://app.zenhub.com/workspaces/main-board-5bd99e4e4b5806bc2befbe27/issues/beeldengeluid/labo-components/221

#221 Update graph for inspect tool

---

app/components/collection/FieldAnalysisStats.jsx
app/components/search/QueryBuilder.jsx
app/components/stats/Histogram.jsx
app/util/ComponentUtil.js
sass/collection/FieldAnalysisStats.scss

**Issue**
https://app.zenhub.com/workspaces/main-board-5bd99e4e4b5806bc2befbe27/issues/beeldengeluid/labo-components/150#issuecomment-444430697

#150 Format number with decimal separators

---

app/util/RegexUtil.js

Removes boolean operators from highlighting and supports wildcards.
? will now highlight any single character. * will match any character(s) until a wordboundary.

Updates RegexUtil

---

app/components/stats/CollectionInspectorLineChart.jsx
app/components/stats/Histogram.jsx
app/components/stats/QuerySingleLineChart.jsx

**Issue:**
https://app.zenhub.com/workspaces/main-board-5bd99e4e4b5806bc2befbe27/issues/beeldengeluid/labo-components/220

Fix issue in graphs when resizing screen

---

app/components/helpers/MessageHelper.jsx
app/components/search/QueryBuilder.jsx
app/components/workspace/projects/query/ProjectQueriesTable.jsx
app/model/QueryModel.js
app/util/TimeUtil.js
package-lock.json
package.json
sass/search/QueryBuilder.scss

@avlisodraude creating this pull request for issue 247, so I can test

PR: Task/#247 update no data for empty aggregations

---

.babelrc
package.json

Enable latest javascript features.
npm install --save-dev babel-preset-stage-0

Enable javascript latest features

---

app/components/collection/DateFieldSelector.jsx
app/components/stats/CollectionInspectorLineChart.jsx
sass/stats/CollectionInspectorLineChart.scss

**Issue:** 
Don't show graph when no data is available and instead display a proper message to the user.
**Issue page:**
https://app.zenhub.com/workspaces/main-board-5bd99e4e4b5806bc2befbe27/issues/beeldengeluid/labo-components/263

#263 Dont display graph when no data is available

---

app/components/collection/CollectionAnalyser.jsx

https://app.zenhub.com/workspaces/main-board-5bd99e4e4b5806bc2befbe27/issues/beeldengeluid/labo-components/281

#281 bug regarding incorrect display of percentage date field

---

app/components/player/transcription/Transcriber.jsx

https://app.zenhub.com/workspaces/main-board-5bd99e4e4b5806bc2befbe27/issues/beeldengeluid/labo-components/297

#297 Bug. Fix highlight in the transcript

---

app/components/stats/ComparisonHistogram.jsx
app/components/stats/QueryComparisonLineChart.jsx

@avlisodraude just so you know I created this PR already

#285 Add xAxis label to compare tool graphs

---

app/ItemDetailsRecipe.jsx
app/components/player/video/FlexPlayer.jsx

#301 Add title for resource in FlexPlayer instead of assetId

---

app/components/search/FieldCategoryCreator.jsx
app/components/search/FieldCategorySelector.jsx
app/util/ComponentUtil.js

issue #308 https://app.zenhub.com/workspaces/main-board-5bd99e4e4b5806bc2befbe27/issues/beeldengeluid/labo-components/308

#308 Cluster fields enhancements

---

app/ItemDetailsRecipe.jsx
app/util/IconUtil.js

#314 Update tab title for Newspaper collection media type

---

app/components/search/FieldCategoryCreator.jsx
app/components/search/FieldCategorySelector.jsx
sass/search/FieldCategoryCreator.scss
sass/search/index.scss

@jblom 
This the same branch as before for issue  #323 but updated with the last master of the end of 27-03-2019.
The previous pull request has been closed since this one will include the last changes along with an updated Master branch.

Updated branch for issue #323. Last master version on 27 march 2019

---

app/SingleSearchRecipe.jsx
sass/search/FieldCategoryCreator.scss

#334 Out Of bounds message

---

app/SingleSearchRecipe.jsx

@jblom 
**There is no issue in the current board/sprint for this branch.**
Modify bookmarking icon in Single Search tool and add a title property so the user will see a message on hover over the btn

Modify bookmar icon and add title to btn in single search bookmarking

---

sass/_variables.scss
sass/recipes/SingleSearchRecipe.scss

#355 Fix issue with Facets and Result set overlaping in Single Search

---

app/components/stats/ComparisonHistogram.jsx
app/components/stats/QueryComparisonLineChart.jsx

Issue regarding no xAxys data (year) in graph for certain query ranges
No issue created for this branch

Issue regarding no xAxys data (year) in graph for certain query ranges

---

sass/_variables.scss
sass/stats/QueryInfoBlock.scss

Issue: https://app.zenhub.com/workspaces/main-board-5bd99e4e4b5806bc2befbe27/issues/beeldengeluid/labo-components/362

#362 UI improvements to Query info blocks in Compare tool
